### ISSUE TITLE
bedparse convert fails on nanocompore bed file

### ISSUE THREAD

**Issue by samir-watson** [tleonardi/bedparse#24]
Hi,
I am having issues with using bedparse to convert an ensembl bed file into UCSC. The bed file was made with nanocompore and the alignments were made to gencode.v33_transcripts which contain the transcript version numbers. 
When I run the following code on a bed file with the header removed
` bedparse convertChr --assembly hg38 --target ucsc WT_v_KO_DRS.2_sig_sites_GMM_logit_pvalue_context_2_thr_0.01.bed`
The script fails on the first line of the bed file and I get the following error;

![Screenshot 2021-03-19 120449](https://user-images.githubusercontent.com/63302622/111771063-8067bf00-88ab-11eb-98ce-cb5aa74db0b0.jpg)

> Traceback (most recent call last):
  File "/home/samirwatson/miniconda3/envs/guitar/bin/bedparse", line 10, in <module>
    sys.exit(main())
  File "/home/samirwatson/miniconda3/envs/guitar/lib/python3.9/site-packages/bedparse/bedparse.py", line 250, in main
    args.func(args)
  File "/home/samirwatson/miniconda3/envs/guitar/lib/python3.9/site-packages/bedparse/bedparse.py", line 121, in convertChr
    translatedLine=bedline(line.split('\t')).translateChr(assembly=args.assembly, target=args.target, suppress=args.suppressMissing, ignore=args.allowMissing, patches=args.patches)
  File "/home/samirwatson/miniconda3/envs/guitar/lib/python3.9/site-packages/bedparse/bedline.py", line 524, in translateChr
    raise BEDexception("The chromosome of transcript "+self.name+" ("+self.chr+") can't be found in the DB.")
bedparse.BEDexception: The chromosome of transcript ENST00000368723.4_ACCTC (chr1) can't be found in the DB.

I have checked the bed file using the validateFormat function and it passed.

**Comment by tleonardi** [comment]
Hi Samir,
based on the error message ("The chromosome of transcript ENST00000368723.4_ACCTC (chr1)") your BED file contains chromosome names in the format "chrN". This is already the UCSC format (whereas Ensembl uses only the chromosomes number without "chr"), so there should be no need to do the conversion..
Just to be sure, you could post the first few lines of the BED file?

**Comment by samir-watson** [comment]
Thanks, I had assumed it was in the ensembl format.
these are the first few lines of the BED file

> chr1    153457946       153457951       ENST00000368723.4_ACCTC 2.23094631245163        -
chr1    8862913 8862918 ENST00000234590.10_GAGCG        2.992140476625321       -
chr1    8861355 8861360 ENST00000234590.10_AGCTG        2.9953364808678695      -
chr1    153991134       153991139       ENST00000651669.1_TCCCT 2.856383270637805       +
chr1    153360815       153360820       ENST00000368738.4_GCCTC 4.2618168289065235      +
chr2    84906599        84906604        ENST00000233143.6_TCTCC 2.8439782562306046      +
chr6    31839648        31839653        ENST00000375638.7_ATGCC 2.391610325417182       +

**Comment by tleonardi** [comment]
Hi @samir-watson,
yes, this is UCSC format. You should be able to load it on the Genome Browser as it is.

best
tom
